language: python
python:
  - "3.6"      # current default Python on Travis CI
before_install:
  - pip install pytest pytest-cov
  - pip install codecov
script:
  - pytest --cov=./
after_success:
  - codecov
